package vista;

import modelo.Album;
import modelo.Artista;
import modelo.Spotruchy;

public class FormularioAlbumes extends javax.swing.JInternalFrame {

    private Spotruchy s = null;

    public FormularioAlbumes(Spotruchy s) {
        this.s = s;
        initComponents();
        this.listaAlbumes.setListData(this.s.getAlbumes().toArray());
        for (Artista a : this.s.getArtistas())
            this.cmbArtista.addItem(a);
        this.cmbArtista.setSelectedItem(null);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAlbumes = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextArea();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbArtista = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Panel de álbumes");

        listaAlbumes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaAlbumes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaAlbumesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaAlbumes);

        jLabel1.setText("Nombre del álbum");

        txtNombre.setColumns(20);
        txtNombre.setRows(5);
        jScrollPane3.setViewportView(txtNombre);

        btnNuevo.setText("Crear");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Artista");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbArtista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cmbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //se crean los métodos para crear un álbum que pertenece a un artista contenido en la lista combo]
        if (this.listaAlbumes.isSelectionEmpty()){
            this.s.crearAlbum(this.txtNombre.getText(), (Artista) this.cmbArtista.getSelectedItem());
        } else {
            Album al = (Album) this.listaAlbumes.getSelectedValue();
            //para realizar la modificación, se toma el valor de la caja de texto, el artista de la lista y se guarda
            this.s.modificarAlbum(al, this.txtNombre.getText(), (Artista) this.cmbArtista.getSelectedItem());
        }
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void listaAlbumesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaAlbumesValueChanged
        if (!this.listaAlbumes.isSelectionEmpty()){
            Album al = (Album) this.listaAlbumes.getSelectedValue();
            this.txtNombre.setText(al.getNombre());
            this.cmbArtista.setSelectedItem(al.getArtista());
        }

    }//GEN-LAST:event_listaAlbumesValueChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //se crean los métodos para crear y/o modificar un artista en/de la lista]
        if (!this.listaAlbumes.isSelectionEmpty()){
            Album al = (Album) this.listaAlbumes.getSelectedValue();
            //para realizar la modificación, se toma el valor de la caja de texto y se guarda
            this.s.eliminarAlbum(al);
        }
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbArtista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaAlbumes;
    private javax.swing.JTextArea txtNombre;
    // End of variables declaration//GEN-END:variables

    public void limpiar() {
        this.txtNombre.setText("");
        System.out.println("Actualizando...");
        Spotruchy.getPersistencia().refrescar(this.s);
        System.out.println("Actualizado");
        this.listaAlbumes.setListData(this.s.getAlbumes().toArray());
        this.listaAlbumes.clearSelection();
    }

}
